-- MySQL Script generated by MySQL Workbench
-- Tue Jun 23 04:17:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ER_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookcity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookcity` ;

-- -----------------------------------------------------
-- Schema bookcity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookcity` ;
USE `bookcity` ;

-- -----------------------------------------------------
-- Table `bookcity`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  `datos_adicionales` VARCHAR(150) NOT NULL,
  `tipo_entrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Libreria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Libreria` (
  `nit` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `telefono` INT NOT NULL,
  `representante_legal` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nit`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `bookcity`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Usuario` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(30) NOT NULL,
  `administrador` BIT NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `Domicilio_id` INT NOT NULL,
  `Libreria_nit` VARCHAR(20) NOT NULL,
  `Usuario_cedula` VARCHAR(20) NOT NULL,
  INDEX `fk_Factura_Domicilio1_idx` (`Domicilio_id` ASC),
  INDEX `fk_Factura_Libreria1_idx` (`Libreria_nit` ASC),
  INDEX `fk_Factura_Usuario1_idx` (`Usuario_cedula` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Libro` (
  `isbn` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `editorial` VARCHAR(20) NOT NULL,
  `autor` VARCHAR(20) NOT NULL,
  `precio` FLOAT NOT NULL,
  `ano_publicacion` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `existencia` INT NOT NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Factura_has_Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Factura_has_Libro` (
  `Factura_id` INT NOT NULL,
  `Libro_isbn` VARCHAR(20) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Factura_id`, `Libro_isbn`),
  INDEX `fk_Factura_has_Libro_Libro1_idx` (`Libro_isbn` ASC),
  INDEX `fk_Factura_has_Libro_Factura1_idx` (`Factura_id` ASC))
ENGINE = InnoDB;

USE `bookcity`;

DELIMITER $$
USE `bookcity`$$
CREATE  TRIGGER Factura_has_Libro_AFTER_INSERT AFTER INSERT ON Factura_has_Libro FOR EACH ROW
BEGIN
update Libro
SET existencia=existencia - NEW.Cantidad
WHERE isbn=new.Libro_isbn;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bookcity`.`Libreria`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookcity`;
INSERT INTO `bookcity`.`Libreria` (`nit`, `nombre`, `direccion`, `telefono`, `representante_legal`) VALUES ('8516548', 'AirBook', 'Calle 45#26-45', 7605025, 'Librerias y Asociados');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bookcity`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookcity`;
INSERT INTO `bookcity`.`Usuario` (`cedula`, `nombre`, `contrasena`, `administrador`) VALUES ('1528958584', 'Camilo', 'Bonilla', 0);
INSERT INTO `bookcity`.`Usuario` (`cedula`, `nombre`, `contrasena`, `administrador`) VALUES ('895485484', 'Andrea', 'Echeverry', 0);
INSERT INTO `bookcity`.`Usuario` (`cedula`, `nombre`, `contrasena`, `administrador`) VALUES ('986251268', 'Andrés', 'Rodríguez', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bookcity`.`Libro`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookcity`;
INSERT INTO `bookcity`.`Libro` (`isbn`, `nombre`, `editorial`, `autor`, `precio`, `ano_publicacion`, `estado`, `existencia`) VALUES ('8.4975944E9', 'Un mundo feliz', 'Debolsillo', 'Aldous Leonard', 25000, 1940, 'Disponible', 10);
INSERT INTO `bookcity`.`Libro` (`isbn`, `nombre`, `editorial`, `autor`, `precio`, `ano_publicacion`, `estado`, `existencia`) VALUES ('8.4998912E9', 'Rebelion de la granja', 'Planeta', 'George Orwell', 20000, 1950, 'Sin stock', 0);

COMMIT;

