-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 23:41:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookcity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookcity` ;

-- -----------------------------------------------------
-- Schema bookcity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookcity` ;
USE `bookcity` ;

-- -----------------------------------------------------
-- Table `bookcity`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Usuario` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(30) NOT NULL,
  `administrador` BIT NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Domicilio` (
  `id_domicilio` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_domicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Drogeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Drogeria` (
  `nit` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `telefono` INT NOT NULL,
  `representante_legal` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nit`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `bookcity`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Factura` (
  `id_compra` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `Usuario_cedula` FLOAT NOT NULL,
  `Domicilio_id_domicilio` INT NOT NULL,
  `Drogeria_nit` FLOAT NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Usuario_cedula`)
    REFERENCES `bookcity`.`Usuario` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Domicilio1`
    FOREIGN KEY (`Domicilio_id_domicilio`)
    REFERENCES `bookcity`.`Domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Drogeria1`
    FOREIGN KEY (`Drogeria_nit`)
    REFERENCES `bookcity`.`Drogeria` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_Usuario1_idx` ON `bookcity`.`Factura` (`Usuario_cedula` ASC) VISIBLE;

CREATE INDEX `fk_Factura_Domicilio1_idx` ON `bookcity`.`Factura` (`Domicilio_id_domicilio` ASC) VISIBLE;

CREATE INDEX `fk_Factura_Drogeria1_idx` ON `bookcity`.`Factura` (`Drogeria_nit` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bookcity`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Libro` (
  `isbn` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `editorial` VARCHAR(20) NOT NULL,
  `autor` VARCHAR(20) NOT NULL,
  `precio` FLOAT NOT NULL,
  `ano_publicacion` INT NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `existencia` INT NOT NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcity`.`Detalle_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcity`.`Detalle_Factura` (
  `Factura_id_compra` INT NOT NULL,
  `Libro_isbn` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `Factura_has_Librocol` VARCHAR(45) NULL,
  PRIMARY KEY (`Factura_id_compra`, `Libro_isbn`),
  CONSTRAINT `fk_Factura_has_Libro_Factura1`
    FOREIGN KEY (`Factura_id_compra`)
    REFERENCES `bookcity`.`Factura` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Libro_Libro1`
    FOREIGN KEY (`Libro_isbn`)
    REFERENCES `bookcity`.`Libro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_has_Libro_Libro1_idx` ON `bookcity`.`Detalle_Factura` (`Libro_isbn` ASC) VISIBLE;

CREATE INDEX `fk_Factura_has_Libro_Factura1_idx` ON `bookcity`.`Detalle_Factura` (`Factura_id_compra` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bookcity`.`Libro`
-- -----------------------------------------------------
START TRANSACTION;
USE `bookcity`;
INSERT INTO `bookcity`.`Libro` (`isbn`, `nombre`, `editorial`, `autor`, `precio`, `ano_publicacion`, `estado`, `existencia`) VALUES ('8.4975944E9', 'Un mundo feliz', 'Debolsillo', 'Aldous Leonard', 25000, 1940, 'Disponible', 3);
INSERT INTO `bookcity`.`Libro` (`isbn`, `nombre`, `editorial`, `autor`, `precio`, `ano_publicacion`, `estado`, `existencia`) VALUES ('8.4998912E9', 'Rebelion de la granja', 'Planeta', 'George Orwell', 20000, 1950, 'Sin stock', 0);

COMMIT;

